services:
  - type: web
    runtime: python
    name: taller-presupuesto
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask db upgrade && gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 4
