"""Add Pedido, Cita, and Inventario models

Revision ID: 1eba3dd5e8f8
Revises:
Create Date: 2025-08-22 18:08:04.133306

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1eba3dd5e8f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("precio_compra", sa.Float(), nullable=True),
        sa.Column("precio_venta", sa.Float(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cita",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("fecha_hora", sa.DateTime(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pedido",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("presupuesto_id", sa.String(length=36), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["presupuesto_id"],
            ["presupuesto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("presupuesto_id"),
    )
    op.create_table(
        "pedido_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pedido_id", sa.Integer(), nullable=False),
        sa.Column("inventario_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventario_id"],
            ["inventario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedido.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pedido_item")
    op.drop_table("pedido")
    op.drop_table("cita")
    op.drop_table("inventario")
    # ### end Alembic commands ###
