"""Make PedidoItem.inventario_id nullable and add description

Revision ID: 3f6eec664c6a
Revises: 1eba3dd5e8f8
Create Date: 2025-08-24 03:20:15.816362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6eec664c6a'
down_revision = '1eba3dd5e8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=False))
        batch_op.alter_column('inventario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_item', schema=None) as batch_op:
        batch_op.alter_column('inventario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
