"""add precio model

Revision ID: 8f5627c93ffe
Revises: pedido_table_add
Create Date: 2025-09-17 00:22:33.753508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5627c93ffe'
down_revision = 'pedido_table_add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index('ix_pedido_presupuesto')
        batch_op.create_index(
            batch_op.f('ix_pedido_presupuesto_id'), 
            ['presupuesto_id'], 
            unique=False
        )
        batch_op.drop_constraint('pedido_presupuesto_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'presupuesto', ['presupuesto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'pedido_presupuesto_id_fkey', 
            'presupuesto', 
            ['presupuesto_id'], 
            ['id'], 
            ondelete='SET NULL'
        )
        batch_op.drop_index(batch_op.f('ix_pedido_presupuesto_id'))
        batch_op.create_index('ix_pedido_presupuesto', ['presupuesto_id'], unique=False)

    # ### end Alembic commands ###
